### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Aceeri** [EmiOnGit/birdylook#1]
Heyo! Might want to license this under MIT / Apache v2 early on (or others if you feel strongly about em). I'm pretty interested in using some of the water code/modifying a bit for my own project.

**Comment by EmiOnGit** [comment]
Uh sure! Thanks for pointing that out

**Comment by EmiOnGit** [comment]
Alright license is added to the project. If all looks good now for you feel free to close the first project issue ;) :1st_place_medal:

**Comment by Aceeri** [comment]
Ty :)
